### PR TITLE
SH110X Driver + Documentation

### PR DESCRIPTION
**Pull request by Reghardt**
Added SH110X OLED display driver and added the necessary documentation.

### CODE REVIEW

**Comment by Reghardt** [comment]
@microsoft-github-policy-service agree

**Comment by pelikhan** [comment]
This looks amazing! @mmoskal do you see anything here that needs updates?

**Review by mmoskal — COMMENTED** [review]
looks great, thank you!

**Comment by pelikhan** [comment]
released!

**Comment by Reghardt** [comment]
Thanks so much!
I look forward to contributing more!

**Pull request merged**
